apiVersion: v1
kind: Service
metadata:
  name: {{ namespace }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: {{ namespace }}
    app.kubernetes.io/part-of: {{ namespace }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ namespace }}
    app.kubernetes.io/part-of: {{ namespace }}